version: '3.8'

services:
    nginx:
        container_name: rsscat-nginx
        image: nginx:alpine
        restart: always
        ports:
            - '80:80'
            - '443:443'
        networks:
            - rsscat
        volumes:
            - /home/ec2-user/rsscat_docker_volumes/nginx:/etc/nginx
            #- /home/ec2-user/rsscat_docker_volumes/build:/usr/share/nginx/html # static website served by nginx
        depends_on:
            - rsscat
    redis:
        container_name: rsscat-redis
        image: redis:6.2.6
        restart: always
        networks:
            - rsscat
        volumes:
            - /home/ec2-user/rsscat_docker_volumes/redis/data:/data
    rsscat:
        container_name: rsscat
        image: rsscat:latest
        restart: always
        networks:
            - rsscat
        env_file:
            - .env
        depends_on:
            - redis

networks:
    rsscat:
        name: rsscat_server_network
        driver: bridge
