version: '3.8'

services:
    #nginx:
    #    image: nginx:alpine
    #    restart: always
    #    ports:
    #        - '80:80'
    #        - '443:443'
    #    networks:
    #        - rsscat
    #    volumes:
    #        - /home/ec2-user/rsscat_docker_volumes/nginx:/etc/nginx
    #        - /home/ec2-user/rsscat_docker_volumes/build:/usr/share/nginx/html
    #    depends_on: # start container after depends are opened.
    #        - rsscat
    #mysql:
    #  image: mysql:8
    #  restart: always
    #  ports:
    #    - '3306:3306'
    #  networks:
    #    - rsscat
    #  volumes:
    #    - /home/ec2-user/rsscat_docker_volumes/mysql:/var/lib/mysql
    #  environment:
    #    - MYSQL_ROOT_PASSWORD=rsscat12345
    redis:
        image: redis:6.2.6
        restart: always
        #ports:
        #  - '6379:6379'
        networks:
            - rsscat
        volumes:
            - /home/ec2-user/rsscat_docker_volumes/redis/data:/data
        # elasticsearch:
        #   image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
        #   restart: always
        #   ports:
        #     - '9200:9200'
        #     - '9300:9300'
        #   networks:
        #     - rsscat
        #   volumes:
        #     - /home/ec2-user/rsscat_docker_volumes/elasticsearch:/usr/share/elasticsearch
        #   kibana:
        #     image: docker.elastic.co/kibana/kibana:8.1.2
        #     restart: always
        #     ports:
        #       - '5601:5601'
        #     networks:
        #       - rsscat
        #     volumes:
        #       - /home/ec2-user/rsscat_docker_volumes/kibana:/usr/share/kibana
    ckiptagger_rsscat:
        image: ckiptagger_rsscat:latest
        restart: always
        #ports:
        #  - '5000:5000'
        networks:
            - rsscat
        volumes:
            - /home/ec2-user/rsscat_docker_volumes/ckiptagger_rsscat:/ckiptagger_rsscat
    #rsscat:
    #  image: rsscat:latest
    #  restart: always
    #ports:
    #  - '3000:3000'
    #  networks:
    #    - rsscat
    #  env_file:
    #    - .env
    #  depends_on: # start container after depends are opened.
    #    - redis
    #    - mysql
    rsscat_worker:
        image: rsscat_worker:latest
        restart: always
        networks:
            - rsscat
        env_file:
            - .env
        depends_on: # start container after depends are opened.
            - redis
    #        - mysql
    rsscat_worker_center:
        image: rsscat_worker_center:latest
        restart: always
        networks:
            - rsscat
        env_file:
            - .env
        depends_on: # start container after depends are opened.
            - redis
    #        - mysql
networks:
    rsscat:
        driver: bridge
